Update visitor for updated Chevrotain vistor validator (#37)
- Upgrade Chevrotain for good measure
- Chevrotain visitor validation required corresponding grammar rules
  for all methods.
- Despite allowing $ names locally as helpers on chevrotain 7.0, it seems this triggered the
  error in 7.1:

Error: Errors Detected in CST Visitor :
Redundant visitor method: <$visit> on CstVisitor CST Visitor
There is no Grammar Rule corresponding to this method's name.
at CstVisitor.validateVisitor (/usr/local/lib/node_modules/bluehawk/node_modules/chevrotain/lib/src/parse/cst/cst_visitor.js:49:23)
at new CstVisitor (/usr/local/lib/node_modules/bluehawk/build/bluehawk/parser/visitor/makeCstVisitor.js:109:19)
at Object.makeCstVisitor (/usr/local/lib/node_modules/bluehawk/build/bluehawk/parser/visitor/makeCstVisitor.js:102:12)
at Bluehawk.parse (/usr/local/lib/node_modules/bluehawk/build/bluehawk/bluehawk.js:86:80)
at Object. (/usr/local/lib/node_modules/bluehawk/build/cli/parseSource.js:198:55)
at step (/usr/local/lib/node_modules/bluehawk/build/cli/parseSource.js:52:23)
at Object.next (/usr/local/lib/node_modules/bluehawk/build/cli/parseSource.js:33:53)
at /usr/local/lib/node_modules/bluehawk/build/cli/parseSource.js:27:71
at new Promise ()
at __awaiter (/usr/local/lib/node_modules/bluehawk/build/cli/parseSource.js:23:12)

- Workaround: externalize the helper method from the class